### ISSUE TITLE
cronjob mode in transfer?

### ISSUE THREAD

**Issue by kholisrag** [artie-labs/transfer#1014]
is it possible to run transfer as cronjob? like per 1 hours / per days?

is its to configure the `flushIntervalSeconds` but I seem not confident since the `transfer` is running as daemon / service, not like the `reader` that can run as one time task, as far as I understand.

Thank you!

**Comment by Tang8330** [comment]
> is it possible to run transfer as cronjob? like per 1 hours / per days?

You can run it however you'd like given that it's either a Docker image or binary executable depending on how you download Transfer. 

We run it as a K8 deployment since it has liveness probes and automatic restart policies.

> is its to configure the flushIntervalSeconds but I seem not confident since the transfer is running as daemon / service, not like the reader that can run as one time task, as far as I understand.

wdym?

**Comment by kholisrag** [comment]
> You can run it however you'd like given that it's either a Docker image or binary executable depending on how you download Transfer.

when I run, its always running, I mean its not stop by itself.

**Comment by Tang8330** [comment]
That's expected :) it's subscribed to the Kafka topic and will flush when there are new rows.

**Comment by kholisrag** [comment]
I see.. okay then, thank you!
