### ISSUE TITLE
Support AWS SQS Queue

### ISSUE THREAD

**Issue by nedyalkov** [artie-labs/transfer#1070]
Allow using AWS SQS as a queue instead of Kafka or Google Pub/Sub.

This will allow AWS users to Artie without setting up Kafka.

**Comment by nedyalkov** [comment]
Hey, team,

I noticed you've implemented Google Pub/Sub, so I believe porting this to SQS should be rather straightforward - just need some adaptor for it.

**Comment by Tang8330** [comment]
Hey @nedyalkov, thanks for the issue.

We looked into supporting SQS before, but we ultimately decided against it.

1. SQS is a message queue, and doesn't follow a pub/sub model. We have replication and history mode are typically implemented as separate Kafka consumer groups that are subscribing to the same Kafka topic to adhere to [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)

2. Ordering is extremely expensive in SQS

3. Mechanics around message acknowledge is lacking. We leverage Kafka transactions to guarantee eventual consistency. We store the latest Kafka offset (which acts as a high watermark) and do not have to store individual messages. 

As you may know, Pub/Sub has the same issue re: [3], and as such we don't use it in Production as the throughput metrics are not great.

---

If you're on the AWS ecosystem, you can spin up a Kafka cluster via MSK. If you don't have the means to do this - we do also offer a managed version of this!

**Comment by nedyalkov** [comment]
Hey @Tang8330 thanks for the explanation. I did not realise you actually need more than one subscriber to implement the data sync to Snowflake. In that case it could be a combination of SNS and SQS, but then it probably becomes a bit too complicated and will probably expensive as well. I'll look deeper into the code (something I didn't do) and if I have further suggestions, I'll log a new issue and add actual technical details.

On the Kafka part - I understand Kafka can be provisioned in AWS, but it brings a ton of complexity and we already have other solutions in place, so bringing in this complexity is not practical for us and probably I'm not the only one.

Once again, thanks for the detailed explanation!
