### ISSUE TITLE
large table with 400+ columns， while sync from postgres to snowflake， logrus_error="can not add field \"topic\"" error="cannot unmarshall key, key: , err: key is nil"

### ISSUE THREAD

**Issue by yunqiqiliang** [artie-labs/transfer#133]
2023-06-24 22:13:24 time="2023-06-24T14:13:24Z" level=warning msg="skipping message..." logrus_error="can not add field \"topic\"" error="cannot unmarshall key, key: , err: key is nil" key= offset=17 value="{\"schema\":{\"type\":\"struct\",\"fields\":[{\"type\":\"struct\",\"fields\":[{\"type\":\"int32\",\"optional\":false,\"default\":0,\"field\":\"id\"},{\"type\":\"string\",\"optional\":false,\"field\":\"first_name\"},{\"type\":\"string\",\"optional\":false,\"field\":\"last_name\"},{\"type\":\"string\",\"optional\":false,\"field\":\"email\"},{\"type\":\"string\",\"optional\":true,\"field\":\"column_added_0001\"},{\"type\":\"string\",\"optional\":true,\"field\":\"column_added_0002\"},{\"type\":\"string\",\"optional\":true,\"field\":\"column_added_0003\"},{\"type\":\"string\",\"optional\":true,\"field\":\"column_added_0004\

**Comment by Tang8330** [comment]
Hey @yunqiqiliang - can you provide the Kafka message along with the partition key?

Looks like the partition key is nil. Does the table have a primary key? If not, you'll likely need to set up a Debezium SMT: https://debezium.io/documentation/reference/stable/transformations/topic-routing.html

**Comment by yunqiqiliang** [comment]
Hi Robin, thanks for your kindly and useful reminder. I really forgot to add a primary key to the postgres source table. While I added index then insert some data into source table , transfer is working normally and create Snowflake destination table, syn data successfully.
One unexpected point is , my source table has 404 columns, and I inserted data is only for 4 columns, no data for other 400 columns. So destination DDL as below:
create or replace TABLE CUSTOMERS.PUBLIC.CUSTOMERS_0010 (
        ID NUMBER(38,0),
        FIRST_NAME VARCHAR(16777216),
        LAST_NAME VARCHAR(16777216),
        EMAIL VARCHAR(16777216)
);
 Other 400 columns are not in the destination table, Does this product behave as expected? I expect that as long as there is data in the source table, even if not every column has a value, the target table schema will include all fields.

My Postgres source table schema as below: column_start=1,column_end=401
# Define column names and types
        columns = [("id", "SERIAL PRIMARY KEY NOT NULL"),
                   ("first_name", "CHARACTER VARYING(255) NOT NULL"),
                   ("last_name", "CHARACTER VARYING(255) NOT NULL"),
                   ("email", "CHARACTER VARYING(255) NOT NULL")]

        for j in range(column_start, column_end):
            col_name = f"column_added_{j:04d}"
            col_type = "CHARACTER VARYING(128)"
            columns.append((col_name, col_type))

My Postgres source table   insert data SQL statement as below,:
for i in range(start, end):
       ***@***.******@***.***>"
        cur.execute(
            f"INSERT INTO inventory.{table_name} (id, first_name, last_name, email) VALUES (%s, %s, %s, %s);",
            (i, "Customer" + str(i), "Test", email)
        )
I only set 4 fields with value, so destination table not appears these 400 columns.
BR，
Qiliang

**Comment by yunqiqiliang** [comment]
Attached 2 images: 
postgres source table:
[image]
[image]

snowflake destination table :
[image]
[image]

**Comment by Tang8330** [comment]
Glad to hear it's working!

With regards to the columns not being automatically created - that's expected for now.

Current workflow:

Transfer will create a column whenever it gets a NOT NULL value. specifically it will do the following:
1. Take the not null value and run this through our typing library
2. The typing library will then inspect the data structure and type and identify if this is a FLOAT, NUMERIC type, etc.
3. We will then diff this against Snowflake and create the column if it does not exists.

We are currently not using Debezium's `fields` envelope to create new columns. Although, I think that would be a fine optimization to make.

**Comment by yunqiqiliang** [comment]
As you mentioned , while Transfer server gets a NOT NULL value, will diff this against Snowflake and create the column if it does not exists. But I could not see this happen, how about it?
1, I updated 1 row  3 fields's value from NULL to some as below:
[image]
2, Then I saw the log from Transfer server:
2023-06-26 13:20:11 time="2023-06-26T05:20:11Z" level=info msg="Merge success, clearing memory..." tableName=customers_0002
3, Then I check Snowflake Destination Table, column_added_0001, column_added_0002, column_added_0003 still not appeared.
[image]
4, Then I udpated raw 1 last_name value as blow,
[image]
And check snowflake destination table again, last_name value was updated, but column_added_0001, column_added_0002, column_added_0003 still not appeared :
[image]
> 
> 
> From: "Robin ***@***.***>
> Date:  Mon, Jun 26, 2023, 12:14
> Subject:  Re: [artie-labs/transfer] large table with 400+ columns， while sync from postgres to snowflake， logrus_error="can not add field \"topic\"" error="cannot unmarshall key, key: , err: key is nil" (Issue #133)
> To: ***@***.***>
> Cc: ***@***.***>, ***@***.***>
> Glad to hear it's working!
> With regards to the columns not being automatically created - that's expected for now.
> Current workflow:
> Transfer will create a column whenever it gets a NOT NULL value. specifically it will do the following:
>  
1. Take the not null value and run this through our typing library
>  
2. The typing library will then inspect the data structure and type and identify if this is a FLOAT, NUMERIC type, etc.
>  
3. We will then diff this against Snowflake and create the column if it does not exists.
>  
We are currently not using Debezium's fields envelope to create new columns. Although, I think that would be a fine optimization to make.

**Comment by yunqiqiliang** [comment]
Good news, while upgraded Transfer  to V2.0.12, the not NULL columns appeared in destination table.
So any change for this issue with Transfer V2.0.12?

**Comment by Tang8330** [comment]
Hey @yunqiqiliang - I don't think the email integration is sending the images through (for reference - https://github.com/artie-labs/transfer/issues/133). Could you try to upload it again?

Which version were you on previously? And what is your `outputSource` within your configuration file?

If you're using `snowflake`, I would recommend moving it to `snowflake_stage` as it has much better throughput and support.

**Comment by yunqiqiliang** [comment]
Hi Robin,
2.0.11 version  on previous and output source format is wal2json. Sure, I am using snowflake as destionation and snowflake_stage is current used.
So far, I could sync table schema with 400+ columns successfully.
But I found the sync perf(only appended data, no update, no delete) is big diff with few columns table, the perf is became very slow while source table with 400+ columns and most of them fields value are NULL. So any skipping NULL fields to increase the perf and reduce the throughput?

**Comment by Tang8330** [comment]
Yep. You'll need to iterate a bit on finding the optimal flush triggers for particular payloads to achieve optimal throughput.

The triggers here are:
1. Flush Interval `flushIntervalSeconds`
2. In memory DB rows (in-mem rows) `bufferRows`
3. In memory DB size `flushSizeKb`

Whichever one triggers first will invoke a flush cycle. If you are trying to test this with a large + wide table, I would:
* Increase (1) to be 180s or higher
* Increase `bufferRows` to be 250k+
* Increase `flushSizeKb` to be 50mb+

For wide tables, a good % of the time spent on flushing is actually executing the DDL and creating the staging table which explains the perf difference between tall vs. wide.
