### ISSUE TITLE
how to config Debezium application.properties

### ISSUE THREAD

**Issue by yunqiqiliang** [artie-labs/transfer#135]
Hi,I have several kilometers tables to be sync from Postgres to snowflake, I want config a rule to map those n
 source tables to 1 topic to n destination tables,followed by this guideline 
https://docs.artie.so/tutorials/debezium-topic-reroute-smt ,
1,in a docket compose,which config file should I put parameters about # Re-route them all to the same topic?
2,how to configure reroute mapping rule such as:
n source tables to 1 topic to n destination tables

n source tables to 1 topic to 1 destination table

1 source tables to 1 topic to n destination tables

BR

**Comment by Tang8330** [comment]
Hey there, which part are you stuck on?

For topic rerouting SMT, Debezium can put all the tables into one topic. 
Then just define one `topicConfig` for the Kafka topic and do not specify `table`. Artie will inspect the individual message within the topic and know which table to map to within the DWH.

**Comment by yunqiqiliang** [comment]
This is my topic config, 
- db: customers
      # tableName: customers_0001
      schema: public
      topic: "dbserver1.inventory.all_tables"
      cdcFormat: debezium.postgres.wal2json
      cdcKeyFormat: org.apache.kafka.connect.storage.StringConverter
This is log while I append one row in source table , no transfer happened, also attached the whole log file:
rt_transfer-connect-1    | 2023-06-27 03:39:44,736 INFO   ||  1 records sent during previous 00:01:14.518, last recorded offset of {server=dbserver1} partition is {transaction_id=null, lsn_proc=34384944, lsn_commit=34384888, lsn=34384944, txId=767, ts_usec=1687837184528566}   [io.debezium.connector.common.BaseSourceTask]
rt_transfer-transfer-1   | time="2023-06-27T03:39:47Z" level=info msg="Flushing via pool..." error="<nil>"
rt_transfer-transfer-1   | time="2023-06-27T03:39:57Z" level=info msg="Flushing via pool..." error="<nil>"

**Comment by Tang8330** [comment]
That looks correct. 

I suspect the SMT is not working as expected. Here's a demo video I put together sometime back explaining how this works: https://www.loom.com/share/05335f564e714c04a3fc4a63ddd024c1

**Comment by Tang8330** [comment]
2 additional things to try to debug.

1. `kafka-topics --list --bootstrap-server BOOTSTRAP_SERVER`, is the topic `dbserver1.inventory.all_tables`?
2. Try logging in this function, specifically log `bytes`. https://github.com/artie-labs/transfer/blob/259c0f1a6cca754c68711be399bc6748d898bbf0/lib/cdc/postgres/debezium.go#L16

**Comment by yunqiqiliang** [comment]
kafka-topics --list result:
1, before I append data into source table(customers):
2023-06-27 06:25:29,912 INFO   ||  Kafka startTimeMs: 1687847129909   [org.apache.kafka.common.utils.AppInfoParser]
__consumer_offsets
connect-configs
connect-offsets
connect-status
dbserver1.inventory.all_tables
2, after I appended data into source table(customers):
2023-06-27 06:26:13,459 INFO   ||  Kafka startTimeMs: 1687847173454   [org.apache.kafka.common.utils.AppInfoParser]
__consumer_offsets
connect-configs
connect-offsets
connect-status
dbserver1.inventory.all_tables
dbserver1.inventory.customers

**Comment by yunqiqiliang** [comment]
Seems Kafka created new topic for source table such as "dbserver1.inventory.customers", not use the expect topic "dbserver1.inventory.all_tables". So SMT does not work, right?
How can I make SMT work?
> From: ***@***.***>
> Date:  Tue, Jun 27, 2023, 14:32
> Subject:  Re: [artie-labs/transfer] how to config Debezium application.properties (Issue #135)
> To: ***@***.***>
> Cc: ***@***.***>, ***@***.***>, ***@***.***>
> kafka-topics --list result:
> 1, before I append data into source table(customers):
> 2023-06-27 06:25:29,912 INFO   ||  Kafka startTimeMs: 1687847129909   [org.apache.kafka.common.utils.AppInfoParser]
> __consumer_offsets
> connect-configs
> connect-offsets
> connect-status
> dbserver1.inventory.all_tables
> 2, after I appended data into source table(customers):
> 2023-06-27 06:26:13,459 INFO   ||  Kafka startTimeMs: 1687847173454   [org.apache.kafka.common.utils.AppInfoParser]
> __consumer_offsets
> connect-configs
> connect-offsets
> connect-status
> dbserver1.inventory.all_tables
> dbserver1.inventory.customers
> 
> 
> From: "Robin ***@***.***>
> Date:  Tue, Jun 27, 2023, 14:02
> Subject:  Re: [artie-labs/transfer] how to config Debezium application.properties (Issue #135)
> To: ***@***.***>
> Cc: ***@***.***>, ***@***.***>
> 2 additional things to try to debug.
>  
1. kafka-topics --list --bootstrap-server BOOTSTRAP_SERVER, is the topic dbserver1.inventory.all_tables?
>  
2. Try logging in this function, specifically log bytes. https://github.com/artie-labs/transfer/blob/259c0f1a6cca754c68711be399bc6748d898bbf0/lib/cdc/postgres/debezium.go#L16

**Comment by yunqiqiliang** [comment]
Hi Robin,
I tested  Bigquery as DWH, result same as Snowflake, SMT not work. Kafka create oen topic for each table but not use the to be routed table.

**Comment by yunqiqiliang** [comment]
while i added below configuration in connector json，smt worked.


# Re-route them all to the same topic.
debezium.transforms=Reroute
debezium.transforms.Reroute.type=io.debezium.transforms.ByLogicalTableRouter
# Matches all the tables under the inventory schema
debezium.transforms.Reroute.topic.regex=(.*).inventory(.*)
# Becomes, topicPrefix.schema.all_tables => dbserver1.inventory.all_tables
debezium.transforms.Reroute.topic.replacement=$1.inventory.all_tables
