### ISSUE TITLE
How to develop a transfer client for a new destination data warehouse?

### ISSUE THREAD

**Issue by yunqiqiliang** [artie-labs/transfer#136]
Hi,I have another data warehouse not in transfer supported destination list. My data warehouse provide jdbc drive and python connector but without a go driver. In this case, How to develop a new transfer client for this new destination data warehouse?

**Comment by Tang8330** [comment]
Hi there, what's the DWH that you'd like to integrate with?

**Comment by yunqiqiliang** [comment]
We are a next generation data infra provider focus on multi cloud and single engine,my destination is our Data Lakehouse, it is just in rc phase to be ga.

**Comment by Tang8330** [comment]
Hm, might be helpful to hop on a quick call to sort this out. I'm at [robin@artie.so](mailto:robin@artie.so).

Just in general though, to integrate - we'll need the following:
1. Establishing a SQL connection (so long as the destination integrates with `go/sql` or can work with an off-the-shelf library such as `pq`).
2. Ability to invoke MERGE or transactions wrapped INSERT, UPDATE and DELETE
3. Ability to invoke COPY INTO or alike so we can parallelize staging table creation and population.
