### ISSUE TITLE
Supporting DynamoDB as a source

### ISSUE THREAD

**Issue by restoretheday** [artie-labs/transfer#157]
DynamoStream exports have a marshalled JSON structure that may match other sources too

**Comment by Tang8330** [comment]
Thanks for creating this issue! Yes DynamoDB is on the roadmap :)

**Comment by Tang8330** [comment]
@restoretheday Happy to say that this is supported now.

1. Reader: https://github.com/artie-labs/reader
2. Set up guide: https://docs.artie.so/real-time-sources/dynamodb
