### ISSUE TITLE
Use BigQuery Storage Write API

### ISSUE THREAD

**Issue by Tang8330** [artie-labs/transfer#184]
https://cloud.google.com/bigquery/docs/write-api

Context https://artie-technologies.slack.com/archives/C04Q7GG6DT9/p1693997817550579

**Comment by Tang8330** [comment]
Potentially doable with the dynamic JSON parser: https://github.com/googleapis/google-cloud-go/blob/7a46b5428f239871993d66be2c7c667121f60a6f/bigquery/storage/managedwriter/integration_test.go#L424-L442

**Comment by claytongentry** [comment]
FYI, https://cloud.google.com/pubsub/docs/bigquery#change_data_capture

This looks like a way simpler alternative to interfacing with Storage Write directly. Pub/Sub supports a native BigQuery subscription, which uses Storage Write under the hood. 

Transfer could simply register those native BigQuery subscriptions to the topics it already registers in Pub/Sub and potentially replace the temp table / merge query workflow altogether.

**Comment by Tang8330** [comment]
Completed: https://github.com/artie-labs/transfer/pull/715
