### ISSUE TITLE
[Enhancement] Remove the need to have primary key within the partition key

### ISSUE THREAD

**Issue by Tang8330** [artie-labs/transfer#33]
Remove this need so we can loosen the requirements that we have around partition keys. In the future, we can explore workloads that have a "custom" primary key (e.g uniq constraint but not specified primary key).

We can get this from the `retData` from an `event`.

**Comment by deepam-kapur** [comment]
Hey @Tang8330! I loved what you are doing and want to contribute. Can you help me from where I can start?

**Comment by deepam-kapur** [comment]
@Tang8330 cool, thanks!
