### ISSUE TITLE
[ASK] is artie-labs/transfer support horizontal scaling?

### ISSUE THREAD

**Issue by kholisrag** [artie-labs/transfer#990]
Hi there,
found this is a great tools that we currently looking for, already try to do replication from postgresql to bigquery using artie-labs/reader and artie-labs/transfer. thanks for creating and sharing this.

wanna ask about is this tools support horizontal scaling? basically I run it as pods in kubernetes and then wanna have horizontal scaling if the load is exceed the threshold.

thank you!

**Comment by Tang8330** [comment]
Hey there, Transfer does work with HPA. For HPA to work you'd want to have more than one partition for the particular topic that you want autoscaled.

Then, you can set up an HPA rule either based on CPU resources, or off of 3rd party metrics like [ingestion lag](https://artie.com/docs/monitoring/available-metrics#metrics)

**Comment by kholisrag** [comment]
I see, we just need to configure the partition on the kafka side yah.

btw, the telemetry things, its only support for datadog now yah, no support for pure prometheus metrics yet?

**Comment by Tang8330** [comment]
Not yet, we do plan to integrate with OTEL, but waiting for it to be a bit more mature before doing so
