### ISSUE TITLE
[ask] whats different between replication and history mode

### ISSUE THREAD

**Issue by kholisrag** [artie-labs/transfer#997]
Hi there,
whats different between replication and history mode? I cannot find docs related to in  code / https://artie.com/docs/open-source/running-artie/options, its only explain we have those 2 choice

Thanks in advance!

**Comment by Tang8330** [comment]
* Replication strives to keep your data with your destination 1:1
* History table will create a separate table (SCD Type 2) [Learn more here](https://www.artie.com/blogs/history-table)
